""" RAY INPUT FILE PARAMETERS """

""" INPUT COLS"""
NC_RAY_CONTRACT = "CONTRACT_TYPE"
NC_RAY_MATUR = "MATUR"
NC_RAY_DEVISE = 'DEVISE'
NC_RAY_MARCHE = 'ATTRIBUTE_3'
NC_RAY_LCR_TIERS = 'ENTITY_TYPE'
NC_RAY_OUTSTANDING = "OUTSTANDINGBUFFER"
NC_RAY_TOTAL_RL = "TOTALRL"
NC_RAY_INFLOW ="INFLOW"
NC_RAY_WINFLOW = "WEIGHTED_INFLOW"
NC_RAY_OUTFLOW = "OUTFLOW"
NC_RAY_WOUTFLOW = "WEIGHTED_OUTFLOW"
NC_RAY_OUTSTANDING0 = "OUTSTANDING0"
NC_RAY_DAR = "DAR"
NC_RAY_BASSIN = "BASSIN"

num_cols_ray_out = [NC_RAY_TOTAL_RL, NC_RAY_OUTSTANDING, NC_RAY_OUTSTANDING0,  NC_RAY_WINFLOW, NC_RAY_WOUTFLOW]
num_cols_ray_all = num_cols_ray_out + [NC_RAY_INFLOW, NC_RAY_OUTFLOW]

""" OUTPUT NCO and RL TABLE"""
NCO_RAY_COEFF = "NCO"
RL_RAY_COEFF = "RL"

""" """
DEF_VALUE_LCR_SHARE=100