
""" """
"""MAIN PARAMS"""
NAME_RUN = "_NAME_RUN"
NAME_RANGE_DAR = "_DAR"
NAME_RANGE_NB_MONTHS_PROJ = "_NB_MOIS_PROJ"
NAME_RANGE_ENTITIES = "_ENTITES"
NAME_RANGE_SOURCES_FOLDER = "_SOURCES_FOLDER"
NAME_RANGE_ALIM_FOLDER = "_ALIM_FOLDER"
NAME_RANGE_SCENARIO_FOLDER = "_SCENARIO_FOLDER"
NAME_RANGE_OUTPUT_FOLDER = "_OUTPUT_FOLDER"
NAME_RANGE_RUN = "_NAME_RUN"

""" OTHER """
NAME_RANGE_ALL_ETABS = "_ALL_ETAB"

"""ALIM PARAMS"""

NAME_RANGE_SC_REF = "_SC_REF_NMD"
NAME_RANGE_MAPPER_RAY = "_MAPPER_RAY"
NAME_RANGE_RATE_INPUT = "_RATE_INPUT"
NAME_RANGE_LIQ_INPUT = "LIQ_INPUT"
NAME_RANGE_TCI_INPUT = "TCI_INPUT"
NAME_RANGE_MODELE_NMD = "_MODELE_NMD"
NAME_RANGE_MODELE_ECH = "_MODELE_ECH"
NAME_RANGE_DET_IG = "DET_IG"
NAME_RANGE_PERIM_NTX = "_PERIM_NTX"
NAME_RANGE_DEPART_DECALE = "_DEPART_DECALE_NTX"
NAME_RANGE_DAR_ZERO_NTX = "_DAR_ZERO"
NAME_RANGE_GENERATE_FWD_NAME = "_GENERATE_FWD_SC"
NAME_RANGE_FWD_SC_NAME = "_FWD_SC_NAME"

"""MOTEUR PARAMS"""

ng_courbes_ajust = "_COURBES_AJUST"
ng_spread_ajust = "_spread_ajust"
nc_nb_mois_pn = "_nb_mois_pn"
nc_type_eve = "_type_eve"
ng_nb_mois_proj = "_NB_MOIS_PROJ"
ng_ind_sortie = "_ind_sortie"
ng_ind_sortie_eve = "_ind_sortie_eve"
ng_col_sortie = "_col_sortie"
ng_force_gp_liq = "_force_gap_liq"
ng_force_gps_nmd = "_force_gaps_nmd"
ng_ajust_only = "_only_ajust"
ng_tla_retraitement = "_TLA_IsRetraitement"
ng_date_refix = "_TLA_NextRefix"
ng_freq_refix = "_FREQ_REFIX_TLA"
ng_compil_sep = "_COMPIL_SEP"
ng_compil_merge = "_FUSIONNER_COMPILS"

""" SCENARIO PARAMS """

RN_MAIN_SC_EVE = "_MAIN_SC_EVE"
RN_STOCK_REF_TX_SC = "_sc_ref_par_default"
RN_TX_PATH = "_TX_FILE_PATH"
RN_LIQ_PATH = "_LIQ_FILE_PATH"
RN_TCI_PATH = "_TCI_FILE_PATH"
RATE_INPUT_FOLDER = "RATE_INPUT"
RN_TYPE_SOURCES = "_type_sources"
RN_DAR = "_DAR"
RN_OUTPUT_DIR = "_output_path"
RN_SCENARIO_FILE_PATH = "_SCENARI_PATH"
RN_SCENARIO_RC_ST = "_SC_RC_ST"
RN_SCENARIO_SRC_DAV = "_table_src_dav"
RN_SCENARIO_LIST_CELL = "_table_des_scénario"
RN_SC_TAUX_USER = "SC TAUX USER"
RN_SHOCKS_FST_CELL = "shocks_fst_cell"
RN_ADD_PN_FST_CELL = "addpn_fst_cell"
RN_STRESS_PN_FST_CELL = "stress_pn_fst_cell"
RN_SC_PN_BPCE_FST_CELL = "_SC_BPCE_ALL"
RN_SOURCES_DIR = "_sources_dir_path"
RN_EUR_HOLIDAYS = '_euro_holidays'
RN_PN_TO_ACTIVATE = '_PN_A_ACTIVER'
RN_MODELE_DAV = '_MODELE_DAV'
RN_ZC_FILE_PATH = "_ZC_EVE_FILE_PATH"
RN_TAB_MODELS = '_SC_MOD'
RN_ETAB_CODIFICATION = '_codification_etab'