from mappings.pass_alm_fields import PASS_ALM_Fields as pa


NC_CONTRAT_BPCE = "CONTRAT BPCE"

SCOPE_MNI_LIQUIDITE = "MNI + LIQUIDITE"


STD_LCR_TIERS = "BAN"


NC_IND3_COMPIL = "IND03"

COL_NUM_COMPIL = ["M" + str(i) if i >= 10 else "M0" + str(i) for i in range(1, pa.MAX_MONTHS_PN + 1)]

NG_DATA_ECH_SC = "_pn_ech"
CONTRATS_AJUST = ["A-AJUST", "P-AJUST"]

NAME_COMPIL_PN = "CompilPN"
NG_REFI_MLT = "_REFI_MLT_BPCE"
NB_CONTRAT_MLT = 3
INDEX_OBLIG = 0
INDEX_OBLIG_SFH = 1
INDEX_SUB = 2
NAME_CONTRAT_OBLIG = "P-OBLIG-OC"
NAME_CONTRAT_OBLIG_SFH = "P-OBLIG-SFH-OC"
NAME_CONTRAT_SUB = "P-TSUB-DD-OC"

NG_SAISONNALITE = "_SAISONALITE_PN_BPCE"
INDEX_ANNEE1 = 0
INDEX_A2_6 = 1

NG_MOIS_BORNE = "_REFI_BPCE_MOIS_BORNE"
NG_EVOL_SUP = "_REFI_BPCE_BORNE_EVOL"
NG_REFI_REPARTITION = "_REFI_CT_REPARTITION"
NG_REFI_MAP = "_REFI_BPCE_CT_MAP"
NG_REFI_MONTANT = "_REFI_CT_MONTANTS"
INDEX_LCR_60 = 0
INDEX_LCR_100 = 1
NC_LCR_TIERS_60 = "LCR TIERS 60%"

CONTRACT_NAME_CALL = "P-TSUB-DD-OC_CALL";
JR_PN_CALL = "1";
AMOR_PROFIL_CALL = "INFINE";
AMOR_PERIODE_CALL = "NONE";
INTERETS_PERIOD_CALL = "NONE";
FIXING_PERIOD_CALL = "";
CAPI_PERIOD_CALL = "NONE"
NC_CALL_BOOK = "BOOK FERMAT GESTION"
NC_CALL_EN_VIE = "En vie"
NC_CALL_DATE = "NEXT CALL DATE"
NC_CALL_DATE_ECH = "DATE ECH"
NC_CALL_DATE_COUPON = "NEXT DATE COUP"
NC_CALL_LAST_DATE_COUPON = "LAST DATE COUP"
NC_CALL_BASE = "BASE"
NC_CALL_DEV = "DEV ENGT"
NC_CALL_INDEX = "INDEX"
NC_CALL_ENCOURS = "CRD CTV"
NC_CALL_MARGE = "MARGE"
NC_CALL_TX_SP = "VAL TX"  # PAS SUR est-ce le taux cible ???