NB_PROJ_TAUX = 300
CN_CODE_FERMAT = 'CODE FERMAT'
CN_CODE_DEVISE = 'DEVISE'
CN_CODE_COURBE = 'CODE COURBE'
CN_CODE_PASSALM = 'CODE PASS_ALM'
CN_TYPE_COURBE = "TYPE"
CN_TYPE2_COURBE = "TYPE 2"
RN_INPUT_TX = "_input_tx"
RN_INPUT_LIQ = "_input_liq"

CN_CODE = 'Code'

CN_BONDS_CODE = 'BOND CODE'
CN_SPREAD = 'SPREAD'
CN_SWAP_CODE = 'SWAP CODE'
CN_TYPE = 'TYPE'
CN_INDEX_FEERIE = 'INDEX FEERIE'

INDEX_EUREONIA_1D = 'EUREONIA1D'
INDEX_EUREURIB_2Y = 'EUREURIB2Y'
INDEX_EUREURIB_5Y = 'EUREURIB5Y'
INDEX_EUREURIB_10Y = 'EUREURIB10Y'

NON_PARALLELE_CHOC_TYPE = ['Aplatissement', 'Pentification', 'Personnalisé']
PROGRESSIF_SHOCK_TYPE = 'Progressif'
CONSTANT_SHOCK_TYPE = 'Constant'

CN_NOM_DE_SCENARIO = 'NOM SCENARIO'
CN_TYPE_SCENARIO = 'TYPE SCENARIO'
CN_ETAB = 'ETAB'
CN_DEVISE = 'DEVISE'
CN_COURBE = 'COURBE'
CN_MATURITY = 'MATURITE'
CN_CHOC = 'VAL. CHOC'
CN_PAS_FR = 'PAS CHOC'
CN_DATE_DEBUT = 'MOIS DEBUT'
CN_DATE_FIN_FR = 'MOIS FIN'
CN_CHOC_SEUIL_1 = 'VAL. CHOC SEUIL 1'
CN_CHOC_SEUIL_2 = 'VAL. CHOC SEUIL 2'
CN_SEUIL_PIVOT_1 = 'SEUIL PIVOT 1'
CN_SEUIL_PIVOT_2 = 'SEUIL PIVOT 2'

CN_START = 'Start'
CN_END = 'End'
CN_SHOCK = 'Shock'
CN_STEP = 'Step'

CN_TERME_SHOCK = 'Terme_Shock'
CN_TERME = 'Terme'

SELECT_ALL_KEYWORD = 'ALL'
SELECT_ALL_LIQ_KEYWORD = 'ALL LIQ'
SELECT_ALL_TX_KEYWORD = 'ALL TX'

ROW_TYPE_LIQ = 'LIQ'
ROW_TYPE_RATE = 'TAUX'
ROW_TYPE_COMPUTED_BOUND = 'COMPUTED BOND'
ROW_TYPE_COMPUTED_TAUX = 'COMPUTED TAUX'


SC_PN_BASE_LINE = 'Sans stress PN'
SC_TX_BASE_LINE = 'Sans choc de TX'