""" ETABS"""
NTX_FORMAT = ["NTX", "SEF", "NPS"]
NON_RZO_ETABS = NTX_FORMAT + ["BPCE", "ONEY"]
MTY_DETAILED_ETAB = ["ONEY"] + NTX_FORMAT
IG_ETAB = NTX_FORMAT + ["BPCE"]

NON_NMD_ST_ETAB = NTX_FORMAT

""" SCOPE"""
MNI_AND_LIQ = "MNI + LIQUIDITE"
MNI = "MNI"
LIQ = "LIQUIDITE"

""" AUTRES PARAMS"""
empty_mapping = "#Mapping"

""" NOM PREFIXES VARIABLES QUANTITATIVES"""
prefixes_amounts = ["LEF", "LEM", "LMN", "LMN EVE", "TEF", "TEM"]

""" GENERIC COLS """
NC_CONTRACT_TEMP = "CONTRACT_TEMP"
NC_PALIER_TEMP = "PALIER_TEMP"
NC_GESTION_TEMP = "GESTION_TEMP"
NC_MATUR_TEMP = "MATUR_TEMP"
NC_DATE_MONTANT = "DATE_MONTANT"

